### ISSUE TITLE
Future updates from WP.com

### ISSUE THREAD

**Issue by szepeviktor** [tomjn/p2020#3]
Hello!

It would be future-proof to add function and class stubs instead of modifying the source several places.
What do you think?

**Comment by szepeviktor** [comment]
- extending classes
- using a child theme
- etc.

**Comment by tomjn** [comment]
The way that it was constructed leaves very, very little room for doing that kind of stuff. Unless there's a way to completely override `functions.php` so that the parent themes functions.php didn't load it wouldn't be possible. I can extend classes but I still have to replace the original instances, and it's not like I can swap them out on a filter or delete them and recreate them.

Even then, I'd have to reproduce 60% of the theme in the child theme. It's just not feasible.

So we'd need co-operation from someone at Automattic for that, so they can move WP.com specific stuff out into functions that can be polyfilled, and only load certain things if the files and functions exist, e.g. `get_user_attributes`, the WPCOM Masterbar class, etc.

**Comment by tomjn** [comment]
Having said that, I'm more than welcome for someone from Automattic to pick up the conditionals and polyfills that I've added here. Some of which have even fixed PHP warnings in the original. Some should also be backwards compatible, such as usiing `site_url` instead of the complicated version wp.com was using

**Comment by szepeviktor** [comment]
Yes, this is a hard error

![kép](https://user-images.githubusercontent.com/952007/89719251-a4365e80-d9c6-11ea-9af2-ae9f8f0b21c4.png)

**Comment by szepeviktor** [comment]
Going through all the changes
https://github.com/tomjn/p2020/compare/60b261eef27e7ed5316c9acdb842fcdef4664045...master
I think everything can be done

1. by replacing functions.php
1. adding 1 file containing all WP.com class/function definitions

I leave it up to you!

**Comment by szepeviktor** [comment]
the `My Team` widget could be simply disabled, a new WordPress-compatible widget can be added

**Comment by tomjn** [comment]
If you want to add files ready for a child theme I'm happy to see some of these items reverted back with polyfills, or unhooked and then replacements hooked in. Some items won't be fixable though, e.g. at the top of some files there are `require` statements for files in `mu-plugins` that don't exist outside of wp.com that cannot be filtered or overriden. `WP_Dotcom_Customize` could be polyfilled in, as could `require_lib`

Also note that the my team widget works, I've rerouted it to users added to the current site

**Comment by szepeviktor** [comment]
After an hour of work: Let me not say how this codebase looks like now.

It needs to be redesigned and reimplemented.
